# creating array from list

In [12]:
import numpy as np

In [13]:
arr_1d = np.array([1,20,35,78])
print("1d_array:", arr_1d)

arr_2d = np.array([[30,88,32,98], [67,33,98,12]])
print("2d_array:", arr_2d,)

1d_array: [ 1 20 35 78]
2d_array: [[30 88 32 98]
 [67 33 98 12]]


# List Vs Array:

In [14]:
py_list = [23,56,21]
print("multiplication of list: ", py_list * 2)

array = np.array([23,56,21]) #element wise multiply
print("multiplication of array: ", array * 2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation time is: ", time.time()-start)

start = time.time()
array = np.arange(1000000)*2
print("\n Array Operaton time is: ", time.time()-start)


multiplication of list:  [23, 56, 21, 23, 56, 21]
multiplication of array:  [ 46 112  42]

 List Operation time is:  0.04613494873046875

 Array Operaton time is:  0.004342317581176758


# Creating arrays from scratch

In [15]:
import numpy as np
zeros = np.zeros((3,3))
print("zeros array: \n", zeros)

ones = np.ones((3,3))
print("ones array: \n", ones)

full = np.full((3,3), 20) #constant value
print("Full array: \n", full)

random  = np.random.random((2,3)) #random numbers
print("random array: \n", random)

sequence = np.arange(0,21,2)
print("squence array: \n", sequence)



zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[20 20 20]
 [20 20 20]
 [20 20 20]]
random array: 
 [[0.01858727 0.03091058 0.89005382]
 [0.30994878 0.77810922 0.37549263]]
squence array: 
 [ 0  2  4  6  8 10 12 14 16 18 20]


# Vector , Matrice and Tensor:

In [16]:
import numpy as np
vector = np.array([2,6,7])
print("vector:",vector)

Matrix = np.array([[3,6,1],[6,9,12]])    #2 dimesions
print("Matrice: ",Matrix)

Tensor = np.array([[[3,2],[7,1],[6,3],[3,2]]]) # more than 2 dimension
print("tensor: ", Tensor)


vector: [2 6 7]
Matrice:  [[ 3  6  1]
 [ 6  9 12]]
tensor:  [[[3 2]
  [7 1]
  [6 3]
  [3 2]]]


# Array Properties:

In [18]:
array = np.array([[2,3,5],[6,9,1]])
print("shape:", array.shape) # array's shape
print("size:", array.size) # array's size
print("type:", array.dtype) # array's type
print("dimension:", array.ndim) # array's dimensions

array = np.array([[2,3,5],[6,9,1.44]]) #float value
print("type:", array.dtype) # array's type

array = np.array([[2,3,5],[6,9,"1.44"]]) #String value
print("type:", array.dtype) # array's type



shape: (2, 3)
size: 6
type: int64
dimension: 2
type: float64
type: <U21


# Array Reshaping:

In [2]:
import numpy as np
array = np.arange(10)
print("Original Array:", array)

Reshape = array.reshape((2,5))
print("reshaped array: ", Reshape)

flatttend = Reshape.flatten() # it provides copy
print("flattend array: ", flatttend)

raveled = Reshape.ravel() # it returns original array, not a copy
print("raveled array: ", raveled) 

transpose = Reshape.T
print("transposed array: ", transpose)



Original Array: [0 1 2 3 4 5 6 7 8 9]
reshaped array:  [[0 1 2 3 4]
 [5 6 7 8 9]]
flattend array:  [0 1 2 3 4 5 6 7 8 9]
raveled array:  [0 1 2 3 4 5 6 7 8 9]
transposed array:  [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
